{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

type: Opaque

stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}